### ISSUE TITLE
github: diagnosticts appear inside the "test results summary"

### ISSUE THREAD

**Issue by mcollina** [MoLow/reporters#109]
![Screenshot 2024-02-01 at 11 56 59](https://github.com/MoLow/reporters/assets/52195/9766051b-f62f-461a-80cb-f5829620b63b)

https://github.com/platformatic/platformatic/actions/runs/7740087396?pr=2040

**Comment by MoLow** [comment]
@mcollina these seem to be actual test diagnostics, not arbitrary stdout:
https://github.com/platformatic/platformatic/blob/dce55105723ee31f927a1da814d6f9d6dab47dc0/packages/sql-graphql/test/subscription.test.js#L112
https://github.com/platformatic/platformatic/blob/dce55105723ee31f927a1da814d6f9d6dab47dc0/packages/sql-graphql/test/subscription.test.js#L231

**Comment by MoLow** [comment]
Duplicates https://github.com/MoLow/reporters/issues/110

**Comment by mcollina** [comment]
Ah! Yes, but those are not really interesting in the report.
