### ISSUE TITLE
[testwatch] Improve file filter

### ISSUE THREAD

**Issue by mikicho** [MoLow/reporters#53]
To make the filter work, we need to enter the complete file name. For instance, in the case of the file named `request-id.test.js`, we have to enter the entire file name `request-id` for the filter to function properly.

![image](https://github.com/MoLow/reporters/assets/11459632/ec04b6fd-d19a-4e54-ae33-e52edb1378cf)

**Comment by MoLow** [comment]
@mikicho are you interested in opening a PR?
it will require adding an extra `*` in the glob expression:

https://github.com/MoLow/reporters/blob/3517b9d14709e122b9aeeaaec6749774ea62c5a0/packages/testwatch/index.js#L59
