### ISSUE TITLE
[testwatch] swallow stdout and console.log

### ISSUE THREAD

**Issue by mikicho** [MoLow/reporters#57]
I have the following test:

```
describe('GET /health', () => {
  before(async () => {
    console.log('hellosssssssssssssssssssssssssssss')
    process.stderr.write('errorrrrrr')
    process.stdout.write('okkkkkkkkkkkkkkk')
  })
})

```

After filtering by file the output is:
![image](https://github.com/MoLow/reporters/assets/11459632/219f8216-acee-41ce-8357-4ca8cc9ce5e8)

expected output;
```
hellosssssssssssssssssssssssssssss
errorrrrrr
okkkkkkkkkkkkkkk
```

It works as excepted when the file filter is inactive (run all tests).

**Comment by mikicho** [comment]
It works as expected on the first run.

**Comment by mikicho** [comment]
I believe that the stdout is being cleared before it flushes because of [this line](https://github.com/MoLow/reporters/blob/main/packages/testwatch/index.js#L82).
I lack expertise in CLIs, so I'm unsure if it's correct and how to resolve this problem. 
Any guidance would be appreciated.

**Comment by MoLow** [comment]
we should probably get an earlier event from node that the test has started running, and not when it is ready for reporting. 
see https://github.com/nodejs/node/issues/46727
