### ISSUE TITLE
[testwatch] run all doesn't clear the filters

### ISSUE THREAD

**Issue by mikicho** [MoLow/reporters#58]
When I filter by file and then click `a` it doesn't clear the file/test filter

**Comment by mikicho** [comment]
Oh.. maybe it's by design... What's the difference between `a` and `c`?

**Comment by MoLow** [comment]
`a` simply runs all the tests with the existing filters
`c` clears filters and then runs all tests
this is the same behavior as jest

![image](https://github.com/MoLow/reporters/assets/8221854/f160b08c-9a70-4ba0-952f-66405ff9ba71)

**Comment by mikicho** [comment]
What's difference between a and enter?
I'm pretty sure a clears filters in Jest.

**Comment by MoLow** [comment]
`a` and `enter` do the same 
I am ok with making a and c do the same I guess

**Comment by mikicho** [comment]
IMO:
`a` - clear filters and run tests
`enter` - run tests without clear filters
`c` is redundant. 

But this is your call. it doesn't really matter to me for now.
