### ISSUE TITLE
Can't start watch reporter if no test suffix

### ISSUE THREAD

**Issue by mikicho** [MoLow/reporters#62]
I use `spec` suffix, so when I run `testwatch` the process exists immediately with:
```
No files found for pattern **/*.test.js
```

I think:
1. I wonder if we shouldn't support both `test` and `spec` as Jest does. But maybe I used to jest, and this is not the practice in other test libraries.
2. I think we shouldn't exist if no test is found in the first run, as we do when we filter out all tests.
3. Maybe the first argument should set the pattern for the files filter? (`testwatch ind` => `**/ind*`)

**Comment by MoLow** [comment]
1. I am ok with changing the default
2. indeed - that sounds like a bug
3. 👍🏻
